############# Russian navigation ##############

# main menu
[[main]]
name = "Домашняя страница"
pageRef = "/"
weight = 1

[[main]]
name = "Обо мне"
pageRef = "/about"
weight = 2

[[main]]
name = "Elements"
pageRef = "/elements"
weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "Pages"
name = "Категории"
pageRef = "/categories"


# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Elements"
pageRef = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
