[[navbar]]
  identifier = "tutorials"
  name = "Туториалы"
  url = "/ru/tutorials/"
  weight = 1
[[navbar]]
  identifier = "changelog"
  name = "Журнал изменений"
  url = "/ru/changelog/"
  weight = 2
